@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class Course {
    name: String
    modules: List<Module>

    getOverallGrade(): double
}

enum Module {
    name: String
    modules: List<Assignment>

    getModuleGrade(): double
    addAssignment(): void
}

class Assignment {
    name: String
    score: double
    weight: double

    calculateGradeLeft(): void
}

class GradeTrackerUI {
    course: Course
    scanner: Scanner

    start(): void
    initializeCourse(): void
    viewOverallGrade(): void
    viewModuleGrades(): void
    updateAssignmentScore(): void
    showMainMenu(): void
}

class GradeTrackerApp {
    main(): void
}

Course "1" --> "*" Module : has a
Module "1" --> "*" Assignment : has a



@enduml